

////////////////// jqury table creator //////////////////////////////////////
// Card  reader RM4
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">Whole Card Reader: 1750304622</div></td>									<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">Antifish: 1750304622-F</div></td>											<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">Magnetic Head: 1750304622-35</div></td>									<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">Main Board: 1750304622-B</div></td>										<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">Gate: 1750304622-C </div></td>												<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">Smart Chip: 1750304622-39</div></td>										<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">Chassis: 1750304622</div></td>												<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">CHD-mot ICT3H5-3AD2792 SecPac2: 1750304622</div></td>						<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">Card Reader Black Plastic Piec: 1750343190</div></td>						<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">Small board with Cable (At The Top) (ESU Board): 01750304622-F</div></td>	<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
// Receipt Printer RM4
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">Receipt Printer TP31 : 01750302898</div></td>								<td align="center"><div class="DeviceTypeStyle">Receipt Printer</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
// Journal printer RM4
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle">Journal Printer TP29 : 01750302907</div></td>								<td align="center"><div class="DeviceTypeStyle">Journal Printer</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
// Dispenser Head RM4
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Som Board : 01750351818 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> BNR Board : 01750301247</div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Calibration Note : 01750211741 </div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Function Test (X01) : 01750221968</div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> In-Output Tray : 01750288271 </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> In-Output Tray Flat Cable : 01750288271-C</div></td>						<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> In-Output Pressure Flat Cable : 01750288271-P</div></td>					<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> In-Output Collector : 01750295447</div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Tape Sensor Flat Cable : 1750295981</div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> PIS1 Flat Cable : 1750295983</div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> PIS2 Flat Cable : 1750295984</div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Magnet Flat Cable : 1750295985</div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Head Upper Transport : 01750291689</div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Head Chassis Transport : 01750291697</div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Head Middle Transport :01750341341</div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Head Lower Transport : 01750290512</div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Head Lower Transport 246 : 01750307726</div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Belt Drive Assembly (Inside HLT) : 01750133367</div></td>					<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Head Safe Transport : 01750298136</div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Camera Module : 01750302850</div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Tape Sensor : 01750266439</div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> UV Sensor : 01750293230</div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Magnet Sensor : 01750295915 </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Real Storage : 01750291701</div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Head Main Board : 01750287366</div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> 450H Escrow :01750291701</div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');

$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Cover UV Sensor : 01750301015 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> UV Sensor Prism : 01750293227 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Flat Cable Upper Camera, Tape Sensor incl. Holder : 01750296744 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Flat Cable Magnet Sensor : 01750295985 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Flat Cable Lower Camera : 01750295984 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Encoder, Speed Sensor : 01750296971 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Sensor interlock 18 mm : 01750270694 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Sensor interlock 18 mm gray assy (new) : 01750335437 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Sensor interlock 28 mm : 01750270693 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Sensor interlock 28 mm gray assy (new) : 01750335439 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');





// Dispenser Safe RM4
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Feed Shaft : 01750106232</div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Dispense Stacking Unit (String) : 01750291752</div></td>					<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Safe Distribution Transport : 01750293073 / 1750339800 </div></td>		<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Safe Vertical Transport : 01750293358</div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> ALL In Box : 01750292967</div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Safe Chassis pre-assed : 01750300723</div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> PCBA_RM3P_Safe_Controller : 01750287368</div></td>						<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Safe Controller : 01750312408</div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
// Others RM4
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> FIB : 01750305474 </div></td>												<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CIB : 1750343365 </div></td>												<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> EPP 08 : 1750346530 </div></td>											<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> PCBA_RM3P_MOVE_Controller : 01750287375</div></td>						<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Shutter : 1750346607</div></td>											<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Shutter Board : 01750149264 </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> 450H / 490C Touch Screen & Bracket : 01750343663 </div></td>				<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> 450H / 490C DNS PCAP Controller : 1750350310 </div></td>					<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> DN Camera (Portrait and Shutter) : 1750312338 </div></td>					<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> DN Portrait Camera Cable : 01750334493 </div></td>						<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> DN Shutter Camera Cable : 01750303048 </div></td>							<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Cage DN : 1750364928 </div></td>											<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Power Supply DN : 1750299984 </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> DSU : 1750281752 </div></td>												<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Euronet Stripper / Tikaway / Feed Wheel : 49267135000A </div></td>		<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Combination Lock : 6642-001 </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">RM4 / V6</div></td></tr>');
// Dispenser Head V6
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> SDU V6 C : 01750310083 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> SDU V6 A : 01750342439 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> V6 Shutter : 01750304916 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> V6 Shutter Board : 01750149264 </div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> HT Head Transport FL RL : 01750310793 </div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> HT Head Transport TTW Short 89 : 01750310814 </div></td>					<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> HT Head Transport TTW Long 246 : 01750310859 </div></td>					<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> HST Head Safe Transport : 01750298136 </div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Paddle Wheels : 01750310083-PW </div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser Head</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
// Dispenser Safe V6
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> SDT Safe Distribution Transport : 01750312524 </div></td>					<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> SDT Safe Distribution Transport (Without SRB) : 01750313763 </div></td>	<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> RRB Reject Retract Box : 01750314096 </div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> PCBA Safe Controller : 01750312718 </div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Upper Extractor : 01750311477 </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Lower Extractor : 01750311478 </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> TMS (DDU Cable) : 01750310807 </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> SCH Safe Chassis : 01750310708 </div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> V6 Dispenser Board : 01750304622 </div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser Safe</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
// Others V6
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Touch Screen 250C : 01750330452 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Touch Screen Controller 250C : 1750350310 </div></td>						<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Customer Screen 250C : 01750301987 </div></td>							<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Cover Lock : 01750156995 </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Turning Lever for Front door : 01750161273 </div></td>					<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> DN 490c Customer Screen : 1750333109 </div></td>							<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> DN 250c Touch Screen : 01750330452 </div></td>							<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> DN 250c Touch DNS PCAP Controller : 1750350310 </div></td>				<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> DN 250c Screen : 01750301987 </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> V6 Fan Kit : 175065671 </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">V6</div></td></tr>');
// Card Reader Diebold Parts
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Card Reader with ASD : 00-104380-000K </div></td>							<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Card Reader Without ASD : 00104378000D </div></td>						<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Card Reader Belt : 49201480000A </div></td>								<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> New Card Reader Board : 89030934000A </div></td>							<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Magnetic Head with Board : 49252159000A </div></td>						<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Magnetic Head : 89031300000A </div></td>									<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
// Receipt Printer Diebold Parts
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Graphical Receipt Printer : 49223820000A </div></td>						<td align="center"><div class="DeviceTypeStyle">Receipt Printer</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Enhanced Receipt Printer : 49257458000B </div></td>						<td align="center"><div class="DeviceTypeStyle">Receipt Printer</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Receipt Printer Belt : 49200585000A </div></td>							<td align="center"><div class="DeviceTypeStyle">Receipt Printer</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Receipt Printer Board 1,2 : 39015109000B/39015104000B </div></td>			<td align="center"><div class="DeviceTypeStyle">Receipt Printer</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
// Journal Printer Diebold Parts
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Old Journal printer : 49247984000A </div></td>							<td align="center"><div class="DeviceTypeStyle">Journal Printer</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> New Journal Printer : 00155446000A </div></td>							<td align="center"><div class="DeviceTypeStyle">Journal Printer</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Journal Belt : 49209561006A </div></td>									<td align="center"><div class="DeviceTypeStyle">Journal Printer</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> journal spindle shaft : 49204644009A </div></td>							<td align="center"><div class="DeviceTypeStyle">Journal Printer</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
// Diebold Screens Parts
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> New Consumer Screen : 49240520000 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Consumer screen : 49201789000F </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Operator Screen : 49240457000A </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
// EPP & FDK Diebold Parts
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> EPP 5 BSC : 492166681700E </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> EPP 5 PCI : 49216680700A </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> EPP 5 Battery : 119056654000A </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> EPP07 : 49249440700B </div></td>											<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> EPP07 bracket : 49226313000B </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> FDK : 00104789000A </div></td>											<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
// Other Diebold Parts
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Old Cage : 00103340240A </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Canyon Cage : 49249260291A </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Sierra Cage : 00105153301A </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Denver Cage : 00104812305D </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Power supply device : 19-054950-000A </div></td>							<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Power Distribution unit 01 : 49211393000A </div></td>						<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> PDU 02 : 49218393000B </div></td>											<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Vega Cable : 49211498000B </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> VGA Card : 39015197000A </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Cage Power Supply : 49212552000B </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Key Board : 49221669000A </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> USB Hub 7 ports : 49211381000A </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
//Dispenser Diebold Parts
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Feed Wheel : 49204018000A </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Take Away : 49016971000F </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Stripper : 49016968000F </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Paddle Wheel : 49201058000B </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> High Belt 4 Picker : 49204013000E </div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Presenter RL 860 : 49211436000A </div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Presenter Belt RL 860 : 29008482000J </div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CAM Rollers : 29008780000A </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> High Belt 5 Picker : 49204013000D </div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Snap Latch Pin for Green LED Picker : 49023555000C </div></td>			<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Dispenser main Board : 49208102000D </div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Stacker : 49211433000A </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Depositor Long Left : 00-104457-000A /00-104453-000A </div></td>			<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Picker with Green LED : 49211432000A </div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> AFD Picker : 49225262000A </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CAPTURE ROLLAR DEPOT PART ONLY : EZMRG3778010 </div></td>					<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> ROLLER, ICT3Q5 : EZMRG4215010 </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Presenter FL 522 : 49211437000B </div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> TCM Board : 49-201152-000D </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> DIVERT DEFLECTOR : 49202783000B </div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Cover, key pad cassette : 49024312000A </div></td>						<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Cam : 49201057000B </div></td>											<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Diebold</div></td></tr>');
// Wincor Card Reader Parts
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Whole Card Reader : 1750173205 </div></td>								<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Magnetic Head : 175017320535 </div></td>									<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Smart Chip : 175017320539 </div></td>										<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> V2CU Card reader shutter : 1770041407 </div></td>							<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> V2CF Card reader control board : 1750173205-29 </div></td>				<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Card Reader LED board : 1750186807 </div></td>							<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Card reader Plastic Piece : 01750144546 </div></td>						<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Askim Board : 01750176088 </div></td>										<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Askim Coil : 01750175035 </div></td>										<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Card Reader Leds : 1750164717 </div></td>									<td align="center"><div class="DeviceTypeStyle">Card Reader</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
// Wincor Receipt Printer Parts
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Whole Receipt TP07 : 1750130744 </div></td>								<td align="center"><div class="DeviceTypeStyle">Receipt Printer</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Whole Receipt TP27 : 1750256247 </div></td>								<td align="center"><div class="DeviceTypeStyle">Receipt Printer</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> BMS of receipt printer TP27 : ETZTP27SENSOR </div></td>					<td align="center"><div class="DeviceTypeStyle">Receipt Printer</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Receipt Printer TP27 Small Gear : Pt1314 </div></td>						<td align="center"><div class="DeviceTypeStyle">Receipt Printer</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Thermal Head of TP27 : 01750256692 </div></td>							<td align="center"><div class="DeviceTypeStyle">Receipt Printer</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Receipt Printer Cutter : 01750256691 </div></td>							<td align="center"><div class="DeviceTypeStyle">Receipt Printer</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
// Wincor Journal Parts
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Journal Printer TP06 : 1750110043 </div></td>								<td align="center"><div class="DeviceTypeStyle">Journal Printer</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
// Wincor Dispenser
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Stacker : 1750109659 </div></td>											<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Presenter RL : 1750239621 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Presenter FL : 1750160110 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Single Reject : 01750109659 </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Single Reject Plastic Piece : 01750057879 </div></td>						<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Leaf Springs : 01750058042_50 </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Clamp / Clamp Chassis : 1750053977 </div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Clamp Motor : 1750042248 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Clamp Locks (Left / Right) : 1750042089 / 1750042090 </div></td>			<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CMD 4-Pully guide for Clamp : 1750157444 </div></td>						<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Stepper Motor : 01750046741 </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> DDU Cable : 01750044668 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Dispenser Main Board : 1750105679 </div></td>								<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CMDv4 Cassettes Board : 1750044878 </div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CMD V4 Chassis 4 Cassettes : 01750130600 </div></td>						<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Upper Extractor : 01750109641 </div></td>									<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Lower Double Extractor : 01750109615 </div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Lower Single Extractor : 01750109613 </div></td>							<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Feed Shaft : 01750035752 </div></td>										<td align="center"><div class="DeviceTypeStyle">Dispenser</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
// CCDM
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM : 01750064500 </div></td>											<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM Chassis : 1750188523 </div></td>										<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM Input Area : 01750168270 </div></td>									<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM input area fork (Flipper) : 1750047826 </div></td>					<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM I/P area flat cables : 1750055614 </div></td>						<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM Input Area Board : 01750102014</div></td>							<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM Intermediate : 01750101952 </div></td>								<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM Alignment : 01750188524 </div></td>									<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM Scanner : 01750154867 </div></td>									<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM ESCROW : 1750177464 </div></td>										<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM Power Supply : 1750160690 </div></td>								<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> CCDM Power Board : 1750155446 </div></td>									<td align="center"><div class="DeviceTypeStyle">CCDM</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
// RM3
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> RM3 Input Area : 01750220330 </div></td>									<td align="center"><div class="DeviceTypeStyle">RM3</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> RM3 Input Area Collector : 01750248000 </div></td>						<td align="center"><div class="DeviceTypeStyle">RM3</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> RM3 Escrow : 01750126457 </div></td>										<td align="center"><div class="DeviceTypeStyle">RM3</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> RM3 Shutter : 1750143750 </div></td>										<td align="center"><div class="DeviceTypeStyle">RM3</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> RM3 String : 01750200435 </div></td>										<td align="center"><div class="DeviceTypeStyle">RM3</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> RM3 String Board : 1750195160 </div></td>									<td align="center"><div class="DeviceTypeStyle">RM3</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> RM3 Feed shaft : 1750239538 </div></td>									<td align="center"><div class="DeviceTypeStyle">RM3</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> RM3 Distribution Gears 5C : 01750256118 </div></td>						<td align="center"><div class="DeviceTypeStyle">RM3</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Escrow / Cassette Socket : 01982677-1 </div></td>							<td align="center"><div class="DeviceTypeStyle">RM3</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Distribution Board : 01750196174 </div></td>								<td align="center"><div class="DeviceTypeStyle">RM3</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> RM3 BVM : 01750249443 </div></td>											<td align="center"><div class="DeviceTypeStyle">RM3</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
// Others
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Touch Screen 2550 : 01750261900 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Touch Screen 2040 : 1750160132 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> 2550 Touch Screen Controller : 1750350314 </div></td>						<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> OLD Touch Controller : 01750154145 </div></td>							<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> New Touch Controller : 01750313465 </div></td>							<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Touch Controller 490 : 1750302529 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Screen RL : 01750262931 </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Supervisor Screen OP06 : 1750267652 </div></td>							<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> EPP 6 : 1750159457 </div></td>											<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> EPP 6 : Shield 1750185055 </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> FDK for 2550 : 1750190139 </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Shutter 2040 & 2060 : 01750239621 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Shutter 2550 & 2560 : 01750166395 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Pro cash Shutter : 01750009924 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Shutter Cable : 1750206755 </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Cage BM : 01750262084 </div></td>											<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Cage BM RM4 : 1750302004 </div></td>										<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Mini Hard 500 GB : Local part </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> ATM HHD 500 GB : ATM HHD 500 GB </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> PDU : 01750150107 </div></td>												<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Power Supply Cage : 1750255322 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Power Supply Device : 1750263469 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Special Electronics : 01750147868 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Special & Concole : 01750235434 </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Locking set (Mosa3den) : 01750196346 </div></td>							<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Mega pixel color camera : 2013110000010B </div></td>						<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Mini USB Camera : AD-H134MCU </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Portrait Camera : 1750265337 </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Shutter Camera : 1750196299 </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Camera Cable : DV3034CUH210-Cable </div></td>								<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> SAS SATA Cable : 1750300509 </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Lock with Keys : 01750172192 </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Lock Plastic Housing : 01750199521 </div></td>							<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> 2550 Fescia Holders : 6542IN-0200N </div></td>							<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
$('#data > tbody').append('<tr><td class="copy"><div Class="DeviceNameStyle"> Combination Lock : 6642-001 </div></td>									<td align="center"><div class="DeviceTypeStyle">Others</div></td><td><div class="DeviceModelStyle">Wincor</div></td></tr>');
